on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libudev-dev
      - name: build frameworkd
        run: |
          cargo install cargo-generate-rpm cargo-deb
          cargo build --release
          cargo generate-rpm
          cargo deb
        working-directory: service
      - name: package gnome-shell extension
        run: zip --filesync --recurse-paths ../`cat metadata.json | jq --raw-output .uuid`.shell-extension-zip .
        working-directory: gnome-extension

      # upload artifacts
      - name: set package names
        run: |
          RPM_PATH=`ls service/target/generate-rpm/*.rpm`
          echo "rpm_path=$RPM_PATH" >> "$GITHUB_ENV"
          echo "rpm_name=`echo $RPM_PATH | rev | cut --delimiter="/" --field=1 | rev`" >> "$GITHUB_ENV"
          
          DEB_PATH=`ls service/target/debian/*.deb`
          echo "deb_path=$DEB_PATH" >> "$GITHUB_ENV"
          echo "deb_name=`echo $DEB_PATH | rev | cut --delimiter="/" --field=1 | rev`" >> "$GITHUB_ENV"
          
          GNOME_EXTENSION_PATH=`ls *.shell-extension-zip`
          echo "gnome_extension_path=$GNOME_EXTENSION_PATH" >> "$GITHUB_ENV"
          echo "gnome_extension_name=$GNOME_EXTENSION_PATH" >> "$GITHUB_ENV"
      - name: Upload frameworkd
        uses: actions/upload-artifact@v4
        with:
          name: frameworkd
          path: service/target/release/frameworkd
      - name: Upload rpm
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.rpm_name }}
          path: ${{ env.rpm_path }}
      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.deb_name }}
          path: ${{ env.deb_path }}
      - name: Upload gnome shell extension
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.gnome_extension_name }}
          path: ${{ env.gnome_extension_path }}